site_name: fabrico-cli
site_url: https://tfs.codearchitects.com:8088/tfs/Code%20Architects/CA-Fabrico/_git/fabrico-cli
site_description: The `Fabrico` command line interface.
site_author: Code Architects

repo_url: https://tfs.codearchitects.com:8088/tfs/Code%20Architects/CA-Fabrico/_git/fabrico-cli
edit_uri: ""

pages:
    - Overview: index.md
    - Guides:
        - Getting started: guides/getting-started.md
        - Concepts:
            - Overview: guides/concepts/concepts-overview.md
        - Samples:
            - NetCore Microservices: guides/samples/microservices-netcore.md
    - Reference:
        - Yaml Reference: references/fabrico-yml.md
    - CLI Reference:
        - Overview: cli-reference/cli-overview.md
        - Commands: cli-reference/cli-commands.md
    - FAQ: faq/index.md

theme: readthedocs

extra_css:
    - css/extra.css

markdown_extensions:
    - toc:
        permalink: 
    - admonition
    - def_list

copyright: Copyright &copy; 2017 <a href="http://www.codearchitects.com">Code Architects</a>.
google_analytics:

plugins:
    - search
